### ISSUE TITLE
Custom space size such such as [u8; 64] always uses heap, no matter the size

### ISSUE THREAD

**Issue by DzmitryFil** [andylokandy/smallbox#15]
Smallbox with size set in bytes always returns .is_heap() -> true, and performs worse then S8 equivalent on 64bit machine (probably because it really uses heap). std::mem::sizeof() for both is 72 bytes. From the limited tests i did, custom byte size box always uses heap, no matter the size chosen.

**Comment by andylokandy** [comment]
You're right, the document is not up to date...
