### ISSUE TITLE
Use `MaybeUninit` directly in the struct in place of `ManuallyDrop`

### ISSUE THREAD

**Issue by toasteater** [andylokandy/smallbox#17]
While the latest "Migrate to Rust 1.36" commit does make an attempt to use `MaybeUninit`, the way it's used is still UB because  `assume_init` is called on uninitialized values: `ManuallyDrop::new(mem::MaybeUninit::<Space>::uninit().assume_init())`.

It should be possible to avoid this by replacing `ManuallyDrop` with `MaybeUninit` directly in the struct.

**Comment by andylokandy** [comment]
Good point. I'll investigate more about it.
