### ISSUE TITLE
There's no guarantee that address is in first usize of fat pointer

### ISSUE THREAD

**Issue by zakarumych** [andylokandy/smallbox#26]
How would `SmallBox` detect if this changes in new rustc version?

**Comment by zakarumych** [comment]
Particularly that assumption is made here in `as_ptr`
https://github.com/andylokandy/smallbox/blob/master/src/smallbox.rs#L223

And in `as_mut_ptr` as well.

**Comment by andylokandy** [comment]
Fixed by https://github.com/andylokandy/smallbox/pull/27
