### ISSUE TITLE
dyn Future

### ISSUE THREAD

**Issue by PonasKovas** [andylokandy/smallbox#38]
Hello,

I want to use a `SmallBox<dyn Future>` in my project, and it seems that it should be fundamentally possible, but there are a few obvious issues:
- [x] ~~Constructing~~ I just realised there is a `coerce` feature for this.
- [ ] Awaiting

For awaiting I think that `Pin<&mut SmallBox<impl Future>>`  should be awaitable somehow, since the stack data is pinned and the potential heap allocation is pinned either way, but I could be wrong.

I'm just seeking some input/insight from you, whether you have considered something like this before, whether you would even accept a PR implementing this into the repository? And if so, maybe you have some ideas how this could be soundly implemented?

Looking forward to your insights

**Comment by PonasKovas** [comment]
Hmm... I could be wrong but I think this might be pretty simple.

I just tried adding a `into_pin(self) -> Pin<SmallBox<T>>` method on `SmallBox<T>`, identical to the one on std `Box`, and it seems to work, `miri` doesn't complain either.

I think this makes sense, because `Pin<SmallBox<T>>` guarantees that `T` is pinned if it's on the heap, and `Future::poll` method takes `Pin<&mut Self>` so this second `Pin` guarantees that `T` is pinned if it's on the stack. Hmmm, I could be overlooking something, I will need to think about this more and do more testing, but this is where I am right now.

**Comment by PonasKovas** [comment]
Hmm I have arrived at another solution, which appears to be sound.

Basically I just implement `Future` for `Smallbox<F> where F: Future`. I think this is sound, because `Future::poll` takes a `Pin<&mut Self>` so that guarantees that the smallbox will not be moved with it's stack data, the heap allocation will not move anyway, and `F` is innacessible safely.

The reason why std `Box` does not do this, is because it implements `Unpin` unconditionally, so the `Pin<&mut Box<F>>` still allows to get `&mut Box<F>`, but with `SmallBox` this cannot be done, as it does not implement `Unpin` when `F: !Unpin`.

I will still need to think about this more, but so far I think this might be the correct solution. Looking forward to hearing your input!

**Comment by andylokandy** [comment]
SmallBox can not guarantee Unpin since the data stored on stack can be moved.

**Comment by PonasKovas** [comment]
Yes but the Future trait takes care of that:
```
fn poll(self: Pin<&mut Self>) -> ...
```
The`Pin` here prevents Self (`SmallBox` here) from being moved on the stack

**Comment by andylokandy** [comment]
well. then why do you need smallbox if you don't need its Unpin guarantee?

**Comment by PonasKovas** [comment]
Because I need to use dynami dispatch `dyn Future` which is unsized

**Comment by PonasKovas** [comment]
I've slept on this idea, thought about in my dreams and I think it's sound. I will make a PR shortly.
