### ISSUE TITLE
Consider using macro for support of unsized values on stable Rust

### ISSUE THREAD

**Issue by RReverser** [andylokandy/smallbox#5]
Even though `Unsize` and `CoerceUnsized` traits are not available on stable Rust, the code casting between compatible sized/unsized variants is still valid and compilable, just can't be expressed via the type system and generics.

This makes me wonder: would it make sense to add top-level macro for `stackbox` and `smallbox`? They would basically contain same code as `new` currently has (most importantly - casts between `&T` and `&U`, everything else can be still hidden into methods), and when expanded, these casts would be validated even by stable Rust, allowing to create unsized SmallBoxes.

**Comment by RReverser** [comment]
I would say (2) doesn't matter as much. As for the first one - yeah, macro will have to use a method that, as similar macros usually do, can be hidden from docs for general consumers with `#[doc(hidden)]` but used by the macro itself.

**Comment by andylokandy** [comment]
`#[doc(hidden)]` doesn't prevent crate user from invoking undefined behaviors or even segfaults. This problem is much more severe than `phf_macro` in which struct fields violation only causes control flow error. I prefer to stick with `Unsize` traits for type system guarantee for now.

**Comment by andylokandy** [comment]
Stable `unsize` feature is no longer viable due to the `CoerceUnsize` commit https://github.com/andylokandy/smallbox/commit/cda7d6bfdd7e1cb8900412296a787b2e55fb29fe.

**Comment by RReverser** [comment]
I still think unsized on stack is possible in a safe way on stable Rust, but if you feel strongly against this idea, it's fair point and I suppose I can implement it in a separate crate.

**Comment by andylokandy** [comment]
Do you have any idea of how to do that?

**Comment by andylokandy** [comment]
Ok, I got it. The `new_unsized` method and the macro initializer. You might make a hard fork for that, it's good for the user to have more options.

**Comment by andylokandy** [comment]
I've come up with a elegant solution about thr macro story. I'll try it out soon.

**Comment by andylokandy** [comment]
👏 👏  Stable unsized type is done!!! Thanks for your help!!

**Comment by RReverser** [comment]
@andylokandy Heh, I've been away for a week, but glad to see this got resolved!
