### ISSUE TITLE
Missing alignment checks

### ISSUE THREAD

**Issue by RReverser** [andylokandy/smallbox#6]
StackBox and SmallBox currently expect any data to be aligned to `usize` but in reality type can have arbitrarily large alignment, and putting it into usize-aligned stack storage can cause all sorts of platform-specific issues.

While there is currently no way to allocate on stack with custom alignment, constructors of these types should at least check that alignment of type not any larger than the expected one, similarly to how they already check type sizes.

**Comment by andylokandy** [comment]
Good point! I'll do it in the next update.
