### ISSUE TITLE
Cannot put sized data into a StackBox / SmallBox with `unsize` feature

### ISSUE THREAD

**Issue by RReverser** [andylokandy/smallbox#7]
Difference in definitions of `new` depending on a feature flag makes it impossible to create a simple sized box when needed. For example, the following code:

```rust
struct S { data: usize, }
let m = StackBox::<S, S1>::new(S { data: 10 }).unwrap();
```

compiles fine with default features, but fails with `unsize` with

> the trait `std::marker::Unsize<stackbox::tests::test_as_ptr::S>` is not implemented for `stackbox::tests::test_as_ptr::S`

I'd suggest exposing same basic interface for sized values via `new` and create a separate feature-controlled `new_unsized` for when it's needed, so that compiler can distinguish and correctly resolve types in both cases.

**Comment by andylokandy** [comment]
Thanks for bringing this up!

This is one of the limitations of `smallbox` now. You can't have a sized `SmallBox` with `unsize` feature flag on. The only formal solution is using `CoerceUnsize`, which can automatically coerce a sized `StackBox` into unsized one, or just keep it sized if coercion is not required. There is a problem on `SmallBox` that `CoerceUnsize` can't be implement for an enum. I also have a solution for it: Turn `SmallBox` into a struct and then track the tag information by ourselves. But it has a trade off that we have to define our own `Box` type to control the heap pointer, which means we would not be able to get a standard `Box<T>` out of it again.

```
I'd suggest exposing same basic interface for sized values via new and create a separate feature-controlled new_unsized for when it's needed, so that compiler can distinguish and correctly resolve types in both cases.
```

It definitely is a solution for the problem, I'll take it into consideration.

**Comment by andylokandy** [comment]
`CoerceUnsize` is implemented for `SmallBox` now and the `new` method only requires `T: Sized`, so you can have either a sized `SmallBox` or an unsized `SmallBox` coerced from the sized one.
